# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: true
contact_links:
  - name: Scoop Discussions
    url: https://github.com/ScoopInstaller/Scoop/discussions
    about: General Scoop questions (not specific to this bucket).
